# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: https://github.com/doublify/pre-commit-rust
    rev: v1.0
    hooks:
      - id: fmt
      - id: clippy
        args: [--workspace, --all-features]
  - repo: local
    hooks:
      - id: tsc
        name: tsc
        entry: pnpm -C frontend run check
        language: system
        pass_filenames: false
        files: ^frontend/
        types_or: [ts, tsx]
      - id: prettier
        name: prettier
        entry: pnpm -C frontend run fmt
        language: system
        pass_filenames: false
        files: ^frontend/
        types_or: [ts, tsx, json, html, yaml]
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-toml
      - id: check-json
      - id: check-added-large-files
